# Generated by Django 2.0.5 on 2018-06-06 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='Inner_Excel',
        ),
    ]
