# Generated by Django 2.0.5 on 2018-06-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_auto_20180606_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inner_excel',
            name='text',
        ),
        migrations.AddField(
            model_name='inner_excel',
            name='inner_excel',
            field=models.FileField(null=True, upload_to='inner_excel/'),
        ),
        migrations.AlterField(
            model_name='inner_excel',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
