# Generated by Django 2.0.5 on 2018-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_auto_20180606_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outter_Excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outter_excel', models.FileField(null=True, upload_to='outter_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inner_excel',
            name='inner_excel',
            field=models.FileField(null=True, upload_to='inner_fiels/'),
        ),
    ]
