# Generated by Django 2.0.5 on 2018-06-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0005_auto_20180606_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_Excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_excel', models.FileField(null=True, upload_to='final_files/')),
            ],
        ),
    ]
