# Generated by Django 2.0.5 on 2018-06-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0006_final_excel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Final_Excel',
        ),
    ]
